services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:latest
    container_name: sonar
    ports:
      - "9000:9000"

  # postgres:
  #   image: postgres
  #   container_name: postgres_sonar
  #   restart: always
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonar
  #     POSTGRES_DB: sonar
  #   ports:
  #     - "5432:5432"

volumes:
  jenkins_home:
