server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:param-ms-db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver

  application:
    name: param-ms
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ali-realm/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: logs/logs.log
